name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar diariamente a medianoche UTC
  workflow_dispatch: # Permitir ejecución manual
  push:
    branches: [main]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necesario para el historial completo de git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git diff --quiet || git commit -m "Auto-update README [skip ci]"
          git push
